# DATA SCIENCE TRAINING SAIL
# PYTHON FOR GENERATIVE AI COURSE
# PYTHON AI SOFTWARE STACK INSTALLATION

# Conda Environment Setup Instructions ----
#  - Using an environment.yml file with conda
#  - Important Terminal Commands:
#    conda env create -f environment.yml
#   conda env create -f /Users/drajalaagift/Documents/GenAI_Training_AJ/environment.yml
#    conda env update -f environment.yml
#    conda env export -n genai_training_aj_sail > envname.yml
#    conda env remove -n genai_training_aj_sail
#    conda env list
#  
# Alternative Using pip & virtual environments:
#  - Create empty virtual environment:
#      Mac: python3 -m venv genai_training_aj_sail
#      Windows: python -m venv genai_training_aj_sail
#  - Activate env:
#      source genai_training_aj_sail activate
#  - Adding packages from requirements.txt
#      Mac: where python
#      Windows: which python
#      path/to/python -m pip install 
#  - Freezing dependencies
#      pip freeze > requirements.txt

name: genai_training_aj_sail
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy==1.26.4
  - pandas==2.2.1
  - matplotlib
  - seaborn
  - plotly==5.19.0
  - scikit-learn==1.3.0
  - xgboost==2.0.3
  - jupyterlab
  - pip
  - pip:
      - pytimetk
      - openai==1.23.6
      - langchain==0.1.16
      - langchain_openai==0.1.3
      - langchain-experimental==0.0.57
      - langchain-community==0.0.34
      - streamlit==1.33.0
      - pypdf==4.2.0
      - google-api-python-client 
      - pytube==15.0.0
      - youtube-transcript-api==0.6.2 
      - PyYAML==6.0.1
      - chromadb==0.5.0
      - watchdog
      - h2o==3.46.0.1
      - quarto==0.1.0 # Make sure to download quarto CLI at https://quarto.org/docs/get-started/
      - sqlalchemy==2.0.29
      #- sqlite==3.41.2
     


